name: "github-action-go"
description: "An example of testing github action with go"

inputs:
  message:
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.message }}
    