on:
  workflow_dispatch:

jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/github-action-go
        with:
          message: Hello World from github action input
